version: '3.7'
services:
  db:
    image: postgres:13.2-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  web:
    build: .
    ports:
      - 5001:5001
    depends_on:
      - db
    env_file:
    - .env 

